# Generated by Django 2.1.15 on 2024-04-22 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0002_userappointment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserAppointment',
        ),
    ]
